version: '3.8'

services:
  app:
    image: your-dockerhub-username/your-app-name:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/samdasu
      SPRING_DATASOURCE_USERNAME: junho
      SPRING_DATASOURCE_PASSWORD: Qwerasdf1234!
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: yourdatabase
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
